### ISSUE TITLE
Mailinglist subscribe

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/dcat-be#1]
The should be a way to subscribe to the mailinglist through a form where a name and e-mail address is given + a link to the archives.

You can find the form (so the logic to create a POST request) and the archive link on this page:

https://lists.okfn.org/mailman/listinfo/dcat-be

**Comment by Dobbelsteen** [comment]
Are we going to use the extra mailinglist features (edit settings, unsubscribe, etc) in this app, or will it be contained to where it is now?
Do we want an unsubscribe input field as well?

**Comment by pietercolpaert** [comment]
No, just the subscribe button. Don't see it as an app, you can implement it using html form only

**Comment by Dobbelsteen** [comment]
Ok, excellent

**Comment by Dobbelsteen** [comment]
Mailing list subscribe form added
