### ISSUE TITLE
Subscribe to mailinglist gives an error

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/dcat-be#10]
When I follow the form, this shows up:

```
You must supply a valid email address.
```

**Comment by Dobbelsteen** [comment]
I forgot the "name" attribute in the input tag, which I think causes the issue.
Will fix asap

**Comment by Dobbelsteen** [comment]
The subscribe button also needed a name value (I think)
Either way, users should be able to subscribe using the form now
