### ISSUE TITLE
A partner section

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/dcat-be#4]
A partner section is needed with logos + link to the people involved in the group.

**Comment by pietercolpaert** [comment]
Confirmed partners:
- [x] Fedict
- [x] Flemish Government
- [x] ProXML
- [x] iMinds
- [x] MMLab
- [x] Open Knowledge Belgium
- [x] Tenforce
- [x] We Open Data

Yet to be confirmed:
- [ ] CIRB
- [ ] Stad Gent
- [ ] Stad Antwerpen
- [ ] Leiedal
- [ ] Kortrijk

Feel free to add your own organisation or suggest others in further comments

**Comment by barthanssens** [comment]
Small remark: Fedict's logo should not mention the word 'Select' (Fedict Select is a brand for recruiting / hiring people, while Fedict-without-select is the organisation / federal public service)

**Comment by Dobbelsteen** [comment]
I updated the logos and added the links (I hope they are all correct)
Also gave them a recolour to fit with the theme

**Comment by pietercolpaert** [comment]
I've pulled this on production: http://dcat.be

**Comment by yvesvanderbeken** [comment]
Hi, you can add HP as well to this list. I assume there is no sponsorship fee implied here?

**Comment by Dobbelsteen** [comment]
Which website do you want the HP partner logo to link to? 
I made it link to http://welcome.hp.com/ for now
Sponsorship is always appreciated, but not implied :)
