### ISSUE TITLE
Links to existing DCAT-BE feeds

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/dcat-be#5]
DCAT BE feeds should be listed. They can be added by cloning this repository, so no form is needed, just an issue created on this repo

e.g., some links that already can be included are available here:
http://data.opendataforum.info/dataset/open-data-portals

**Comment by barthanssens** [comment]
FYI, I'm planning to put a few dcat files on github in the upcoming weeks (https://github.com/Fedict/datagovbe/tree/master/catalogs)

**Comment by barthanssens** [comment]
Statbel and Mobilit available as DCAT-AP(-ish) feed

**Comment by Dobbelsteen** [comment]
At the moment I'm linking 5 live-demos on the website:
- DCAT Kortrijk 
- DCAT TheDataTank demo 
- Metadata Ghent 
- Metadata Antwerp 
- Metadata Brussels

I feel like that should be plenty of examples for now, we might be able to make a more detailed catalog of all the Data Catalogs available in a future version of the website

**Comment by pietercolpaert** [comment]
I feel like a complete catalog is really the core goal of the website. The URIs to DCAT feeds, can't they be stored in a JSON-LD in the root of this repo?

**Comment by Dobbelsteen** [comment]
I've been working on a catalog for the datasets in JSON-LD format.
I'm not 100% sure how to format it though, do you want something like this?
http://demo.thedatatank.com/dcat/demo.jsonld

This format contains a catalog with all the sets, definitions for all the datasets, as well as the distribution layer (which I assume would be a reference to "http://data.kortrijk.be/api/dcat" for example)

These datasets are already defined within themselves, so should I define them a second time in our own catalog? I'm talking about things like author, description, published date. Or should I rely solely on the URIs?

**Comment by pietercolpaert** [comment]
Can you start with creating a simple JSON-LD structure where you keep the @context empty for now? Most important right now is that we can quickly add new datasets without editing the main html file
