### ISSUE TITLE
Explain relation DCAT - DCAT-AP - DCAT-BE

### ISSUE THREAD

**Issue by Dobbelsteen** [openknowledgebe/dcat-be#6]
At the moment we give a rough overview of DCAT in general, along with some examples.
We don't explain the relation/differences between DCAT -> DCAT-AP -> DCAT-BE.

This is a key component of the site and should be well written

**Comment by pietercolpaert** [comment]
In short:
DCAT is the W3C standard adopted by the European Commission as [DCAT-AP](https://joinup.ec.europa.eu/asset/dcat_application_profile/description). DCAT-AP extends DCAT by making some fields mandatory, recommended and optional, cfr. [the overview image](https://joinup.ec.europa.eu/system/files/project/dcat-ap_4.png). DCAT-BE now extends DCAT-AP by adding a theme taxonomy for Belgium and maybe in the future making some other fields mandatory (to be decided at meetings)

**Comment by Dobbelsteen** [comment]
> The DCAT-BE standard is derived from the [DCAT-AP](https://joinup.ec.europa.eu/asset/dcat_application_profile/description) standard, which in turn is derived from the W3C DCAT standard. DCAT-AP is an extension to DCAT adopted by the European Commission. DCAT-AP makes some fields mandatory, recommended and optional compared to DCAT, cfr. [the overview image](https://joinup.ec.europa.eu/system/files/project/dcat-ap_4.png).
> DCAT-BE extends DCAT-AP by adding a theme taxonomy for Belgium and maybe in the future making some other fields mandatory (which will be discussed and decided upon in meetings)

A lot of DCATs inthere, but this is the current description I put on the site.
Can we use this for now or do we need to improve/expand this
