### ISSUE TITLE
meetings json

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/dcat-be#8]
The JSON feed of the meetings and meetings minutes:
- Can you make sure that it's a valid JSON-LD? Add `@context` to it and make sure all the words used translate to URIs
- Can you put it in the root of this repo? Now the extra folder doesn't make much sense?

**Comment by Dobbelsteen** [comment]
Done and done.
The meetings-ld file can also be updated freely (by adding new meetings at the end of the events array)
The event listing is done automatically. The soonest upcoming event is listed in the upcoming events section, and the last 5 meetings are listed in the past meetings section.
